Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,80 +1,190 @@
 name: Update Free Nodes
 
+
 permissions:
+
   contents: write
+
   pages: write
+
   id-token: write
 
+
+
 on:
+
+
   schedule:
+
+
     - cron: "0 */6 * * *"
+
 
   workflow_dispatch:
 
 
+
+
 jobs:
+
+
 
   build:
 
+
+
     runs-on: ubuntu-latest
+
+
 
     steps:
 
+
+
       - name: Checkout
-        uses: actions/checkout@v4
+
+        uses: actions/checkout@v5
+
+        with:
+
+          fetch-depth: 0
+
+
+
 
 
       - name: Setup Python
-        uses: actions/setup-python@v5
+
+        uses: actions/setup-python@v6
+
         with:
+
           python-version: "3.x"
 
 
+
+
+
       - name: Install requirements
+
         run: |
+
           pip install -r requirements.txt
 
 
+
+
+
       - name: Install Xray
+
         run: |
+
           python xray_setup.py
 
 
+
+
+
       - name: Run generator
+
         run: |
+
           python main.py
 
 
+          echo "===================="
+
+          echo "XRAY LOG"
+
+          echo "===================="
+
+
+          cat xray.log || true
+
+
+
+          echo "===================="
+
+          echo "XRAY ERROR"
+
+          echo "===================="
+
+
+          cat xray_error.log || true
+
+
+
+
+
       - name: Save result
+
         run: |
+
+
           git config user.name github-actions
+
           git config user.email github-actions@github.com
+
+
+
           git add .
+
+
+
           git commit -m "auto update" || echo "no changes"
+
+
+
+          git pull --rebase origin main
+
+
+
           git push
 
 
+
+
+
       - name: Upload Pages artifact
-        uses: actions/upload-pages-artifact@v3
+
+        uses: actions/upload-pages-artifact@v4
+
         with:
+
           path: ./output
+
+
+
+
+
 
 
 
   deploy:
 
+
+
     needs: build
+
+
 
     runs-on: ubuntu-latest
 
 
+
     environment:
+
 
       name: github-pages
 
 
+
+
     steps:
 
+
+
       - name: Deploy Pages
+
 
         uses: actions/deploy-pages@v4
